name: CI/CD Pipeline

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Git Pull
      run: |
        cd /home/ditoihkam/fe-dumbmerch2
        git pull

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: SSH Login
      uses: appleboy/ssh-action@master
      with:
        host: 103.175.221.143
        username: ditoihkam
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: 'echo "Logged in to SSH"'


    - name: Build and Push Docker Image
      run: |
        docker build -t kelompok2/fe-dumbmerch2 .
        docker push kelompok2/fe-dumbmerch2
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 103.175.221.143
        username: ditoihkam
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ditoihkam/fe-dumbmerch2
          docker compose up -d
